#!/usr/bin/env bash
# Transfers a file from our client to a server
# If the number of parameters passed is less than 4
# Show an error message and exit
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/
