#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

apt-get update -y -qq
apt-get install nginx -y

# starting nginx service
service nginx start

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Restarting nginx
service nginx restart