#!/usr/bin/env bash
# 404 page configuration

# Define the replacement string
string_to_replace="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

# Use sed to replace the 'listen 80 default_server;' line with the new configuration
sudo sed -i "s/listen 80 default_server;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Validate Nginx configuration
if sudo nginx -t; then
    # Restart Nginx service if configuration is valid
    sudo service nginx restart
else
    echo "Nginx configuration is invalid. Please check the configuration."
    exit 1
fi
