#!/usr/bin/env bash
# This script configures nginx so that its http response

sudo apt-get update
sudo apt-get install -y nginx

custom_header="add_header X-Served-By \$hostname;"
nginx_conf="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _;/a $custom_header" $nginx_conf

sudo service nginx restart