#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy


echo "
frontend john
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 491826-web-01  54.85.109.210:80 check
    server 491826-web-02  35.168.8.91:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
