#!/usr/bin/env bash
# creating ssh login
#setting up ssh agent

eval $("ssh-agent")

# add ssh idetfile file in computer memory

ssh-add ~/.ssh/school
# connect useing username and ip address
ssh ubuntu@54.85.109.210
