#!/usr/bin/env bash
# block port packet firewall filtering

sudo apt install -y ufw 
sudo ufw default allow outgoing
sudo ufw default deny incomeing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
echo "y" | sudo ufw enable 
